### Site info:
title: SEMBA
tagline: EMC Broadband simulator
locale: en_US
host: 0.0.0.0
### Personal info and site tools info:
favicon:     "/images/favicon.ico"

### Site setting:
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Archives: "Archives"
      Categories: "Categories"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      News: "News"
      Contact: "Contact"
      OpenSemba: "OpenSEMBA"
      BooksAndDocs: "Papers"
      
### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
